### PR TITLE
Elise

### PR DESCRIPTION
**Pull request by elise1914347**
changesNavbar

### CODE REVIEW

**Review by yamuben — CHANGES_REQUESTED** [review]
- Align all items , niba ari ugutangirira kuruhande zose abe ariho zitangirira.
- once i do scroll up, the navigation should stay on top.
-

**Comment by elise1914347** [comment]
> 

navbarhomepage

**Comment by yamuben** [comment]
> Reference in new issue
> Edit
> Hide
> Delete

your PR is going to be merged, but you have to revamp the menu:
- Home
- Products
- Retailers
- Contact Us
-

**Comment by elise1914347** [comment]
> > Reference in new issue
> > Edit
> > Hide
> > Delete
> 
> your PR is going to be merged, but you have to revamp the menu:
> 
> * Home
> * Products
> * Retailers
> * Contact Us

innovation

**Pull request merged**
